ConCon/Models/MapViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ConCon.Models
{
    public class MapViewModel
    {
        public ApplicationUser user { get; set; }

        public List<EventViewModel> events { get; set; }

    }
    public class Meta
    {
        public int per_page { get; set; }
        public int total { get; set; }
        public int page { get; set; }
        public int took { get; set; }
        public object geolocation { get; set; }
    }

    public class InHand
    {
    }

    public class Location
    {
        public double lat { get; set; }
        public double lon { get; set; }
    }

    public class Venue
    {
        public string url { get; set; }
        public double score { get; set; }
        public Location location { get; set; }
        public string address { get; set; }
        public int num_upcoming_events { get; set; }
        public string state { get; set; }
        public string name_v2 { get; set; }
        public string postal_code { get; set; }
        public int id { get; set; }
        public List<object> links { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string display_location { get; set; }
        public string slug { get; set; }
        public string extended_address { get; set; }
        public string timezone { get; set; }
        public string country { get; set; }
        public double popularity { get; set; }
        public bool has_upcoming_events { get; set; }
    }

    public class Stats
    {
        public int event_count { get; set; }
    }

    public class Genre
    {
        public string name { get; set; }
        public bool primary { get; set; }
        public string slug { get; set; }
        public int id { get; set; }
    }

    public class Taxonomy
    {
        public int? parent_id { get; set; }
        public int id { get; set; }
        public string name { get; set; }
    }

    public class Images
    {
        public string huge { get; set; }
    }

    public class Performer
    {
        public Stats stats { get; set; }
        public string type { get; set; }
        public int id { get; set; }
        public object home_venue_id { get; set; }
        public string image { get; set; }
        public string short_name { get; set; }
        public object colors { get; set; }
        public List<Genre> genres { get; set; }
        public double popularity { get; set; }
        public int num_upcoming_events { get; set; }
        public string url { get; set; }
        public double score { get; set; }
        public string image_attribution { get; set; }
        public List<Taxonomy> taxonomies { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public Images images { get; set; }
        public object divisions { get; set; }
        public string image_license { get; set; }
        public bool has_upcoming_events { get; set; }
        public bool? primary { get; set; }
    }

    public class Taxonomy2
    {
        public int? parent_id { get; set; }
        public int id { get; set; }
        public string name { get; set; }
    }

    public class Stats2
    {
        public int? listing_count { get; set; }
        public double? average_price { get; set; }
        public double? lowest_price_good_deals { get; set; }
        public double? lowest_price { get; set; }
        public double? highest_price { get; set; }
    }

    public class EventViewModel
    {
        public string datetime_utc { get; set; }
        public Venue venue { get; set; }
        public int id { get; set; }
        public List<Performer> performers { get; set; }
        public string datetime_local { get; set; }
        public bool time_tbd { get; set; }
        public string short_title { get; set; }
        public bool is_open { get; set; }
        public double popularity { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public double score { get; set; }
        public string type { get; set; }
        public List<Taxonomy2> taxonomies { get; set; }
        public bool datetime_tbd { get; set; }
        public bool date_tbd { get; set; }
        public string announce_date { get; set; }
        public List<object> links { get; set; }
        public string visible_until_utc { get; set; }
        public string created_at { get; set; }
        public Stats2 stats { get; set; }
    }

    public class MapViewRootObject
    {
        public Meta meta { get; set; }
        public InHand in_hand { get; set; }
        public List<EventViewModel> events { get; set; }
    }
}

ConCon/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace ConCon.Controllers
{
    public class CalendarController : Controller
    {
        // GET: Calendar
        public ActionResult GoogleAuthenticationView()
        {
            return View();
        }

    }
}

ConCon/Controllers/MapController.cs
using ConCon.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using Newtonsoft.Json;
using System.Web.Mvc;

namespace ConCon.Controllers
{
    public class MapController : Controller
    {
        // GET: Map

        public ActionResult MapView(int id)
        {
            var artists = SearchSimilar(id);
            List<string> artistNames = new List<string>();
            foreach (var artist in artists)
            {
                artistNames.Add(artist.name);
            }
            List<string> splitArtists = ArtistSplit(artistNames);
            return View(EventApiCall(splitArtists));
        }
        private List<string> ArtistSplit(List<string> artistNames)
        {
            List<string> correctedNames = new List<string>();
            foreach (string artist in artistNames)
            {
                if (artist.Contains(" "))
                {
                    string correctedName = null;
                    
                    string[] splitName = artist.ToLower().Split();
                    foreach (string name in splitName)
                    {
                        correctedName += name + "-";
                    }
                    string artistName = correctedName.Remove(correctedName.Length - 1);
                    correctedNames.Add(artistName);
                }
                else
                {
                    string lowerArtist = artist.ToLower();
                    correctedNames.Add(lowerArtist);
                }
            }
            return correctedNames;
        }
        private List<EventViewModel> EventApiCall(List<string> artists)
        {
            var settings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                MissingMemberHandling = MissingMemberHandling.Ignore,
            };
            List<EventViewModel> events = new List<EventViewModel>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.seatgeek.com/2/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                foreach (string artist in artists)
                {
                    string url = "https://api.seatgeek.com/2/events?performers.slug=" + artist + "&client_id=ODExNjMyNnwxNDk5Nzg0NzQxLjEy";
                    HttpResponseMessage response = client.GetAsync(url).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var jsonString = response.Content.ReadAsStringAsync();
                        MapViewRootObject result = JsonConvert.DeserializeObject<MapViewRootObject>(jsonString.Result,settings);
                        foreach (EventViewModel Event in result.events)
                        {
                            events.Add(Event);
                        }
                    }
                }
            }
            return events;
        }
        private List<SimilarPerformerViewModel> SearchSimilar(int origId)
        {
            List<SimilarPerformerViewModel> ResultList = new List<SimilarPerformerViewModel>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.seatgeek.com/2/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                string url = "https://api.seatgeek.com/2/recommendations/performers?performers.id=" + origId + "&client_id=ODExNjMyNnwxNDk5Nzg0NzQxLjEy";
                var response = client.GetAsync(url).Result;
                if (response.IsSuccessStatusCode)
                {
                    var result = response.Content.ReadAsStringAsync();
                    SimilarPerformerRootObjectViewModel PerformerList = JsonConvert.DeserializeObject<SimilarPerformerRootObjectViewModel>(result.Result);
                    foreach (RecommendationViewModel rec in PerformerList.recommendations)
                    {
                        SimilarPerformerViewModel performer = new SimilarPerformerViewModel();
                        performer = rec.performer;
                        ResultList.Add(performer);
                    }
                }
            }
            return ResultList;
        }
    }
}

ConCon/Views/Map/MapView.cshtml
@model IEnumerable<ConCon.Models.EventViewModel>
@using Newtonsoft.Json
@{
    ViewBag.Title = "MapView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<html>

<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />   
    <script src="http://maps.google.com/maps/api/js?key=AIzaSyCZwQiJCGkSJzK1K_ZKGIs_e045g3RjELU"
            type="text/javascript"></script>
</head>




<body>
    <h2>Google Maps View of Events</h2>
    <h4>Click points for more infomation</h4>
    <div id="map" style="width: 800px; height: 430px; display: block; margin: 0 auto"></div>
  <br />
    <p>@Html.ActionLink("Go to Google Calendar", "GoogleAuthenticationView", "Calendar", new { }, new { @class = "Search" })</p>
    <script type="text/javascript">
        var data = @Html.Raw(Json.Encode(Model));
        console.log(data);

        var dataLength = data.length
        var locations = [];
        for (var e = 0; e < dataLength; e++)
        {
            var eventInfo = '<div id="content">' +
                   '<div id="siteNotice">' +
                   '</div>' +
                   '<h1 id="firstHeading" class="firstHeading"></h1>' +
                   '<div id="bodyContent">' +
                   '<p venueName>Venue Name: ' + data[e].venue.name + '</p>' +
                   '<p eventName>Artist Name: ' + data[e].performers[0].short_name + '</p>' +
                   '<p>Event Address: ' + data[e].venue.address + '</p>' +
                   '<p>Event Time: ' + data[e].datetime_local + '</p>' +
                   '<p>Event Name: ' + data[e].title + '</p>' +
                   '<p>Buy Tickets <a href="' + data[e].url + '">Here</a></p>' +
                   '</div>' +
                   '</div>';     
            var eventObj = { eventInfo: eventInfo, lat: data[e].venue.location.lat, long: data[e].venue.location.lon}         
            locations.push(eventObj);
        }
        

        var i = 0;      

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 4,
      center: new google.maps.LatLng(data[0].venue.location.lat, data[0].venue.location.lon),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infowindow = new google.maps.InfoWindow();

    var marker;

    for (i = 0; i < locations.length; i++) {
       
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i].lat, locations[i].long),
        map: map
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i].eventInfo);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }
    </script>
</body>
</html>