ConCon/Models/ArtistSearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ConCon.Models
{
    public class ArtistSearchViewModel
    {
        public string Search { get; set; } 
    }
    public class SearchSimilarViewModel
    {
      
        public string Search { get; set; }
    }
    public class GenreViewModel
    {
        public string name { get; set; }
        public bool primary { get; set; }
        public int id { get; set; }
        public string slug { get; set; }
    }
    public class PerformerViewModel
    {
        public double popularity { get; set; }
        public string image { get; set; }
        public List<object> links { get; set; }
        public double score { get; set; }
        public string name { get; set; }
        public List<GenreViewModel> genres { get; set; }
        public int id { get; set; }
        public string url { get; set; }
    }
    public class ArtistSearchRootObjectViewModel
    {
        public List<PerformerViewModel> performers { get; set; }
    }
    //===================================================
    public class SimilarArtistGenreViewModel
    {
        public bool primary { get; set; }
        public string name { get; set; }
        public int id { get; set; }
        public string slug { get; set; }
    }

    public class SimilarPerformerViewModel
    {
        public double score { get; set; }
        public string type { get; set; }
        public string url { get; set; }
        public string image { get; set; }
        public string name { get; set; }
        public int id { get; set; }
        public List<SimilarArtistGenreViewModel> genres { get; set; }
        public int num_upcoming_events { get; set; }
        public int OrigId { get; set; }
    }
    public class RecommendationViewModel
    {
        public SimilarPerformerViewModel performer { get; set; }
    }

    public class SimilarPerformerRootObjectViewModel
    {
        public List<RecommendationViewModel> recommendations { get; set; }
    }
}

ConCon/Controllers/ArtistSearchController.cs
using ConCon.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace ConCon.Controllers
{
    public class ArtistSearchController : Controller
    {
        // GET: ArtistSearch
        public ActionResult Index()
        {
            return View();
        }
        //GET: Search
        public ActionResult Search()
        {
            return View();
        }
        public ActionResult SearchResult(ArtistSearchViewModel model)
        {
            List<PerformerViewModel> ResultList = new List<PerformerViewModel>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.seatgeek.com/2/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                string url = "https://api.seatgeek.com/2/performers?q=" + model.Search + "&client_id=ODExNjMyNnwxNDk5Nzg0NzQxLjEy";
                var response = client.GetAsync(url).Result;
                if (response.IsSuccessStatusCode)
                {
                    var result = response.Content.ReadAsStringAsync();
                    ArtistSearchRootObjectViewModel PerformerList = JsonConvert.DeserializeObject<ArtistSearchRootObjectViewModel>(result.Result);
                    foreach (PerformerViewModel perf in PerformerList.performers)
                    {
                        PerformerViewModel performer = new PerformerViewModel();
                        performer.name = perf.name;
                        performer.id = perf.id;
                        performer.genres = perf.genres;
                        performer.score = perf.score;
                        performer.image = perf.image;
                        performer.popularity = perf.popularity;
                        performer.url = perf.url;

                        ResultList.Add(performer);

                    }
                }
            }
            return View(ResultList);
        }
        public async Task<ActionResult> SearchSimilar(int id)
        {
           
            List<SimilarPerformerViewModel> ResultList = new List<SimilarPerformerViewModel>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.seatgeek.com/2/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                string url = "https://api.seatgeek.com/2/recommendations/performers?performers.id=" + id + "&client_id=ODExNjMyNnwxNDk5Nzg0NzQxLjEy";
                var response = client.GetAsync(url).Result;
                if (response.IsSuccessStatusCode)
                {
                    var result = await response.Content.ReadAsStringAsync();
                    SimilarPerformerRootObjectViewModel PerformerList = JsonConvert.DeserializeObject<SimilarPerformerRootObjectViewModel>(result);
                    foreach (RecommendationViewModel rec in PerformerList.recommendations)
                    {
                            SimilarPerformerViewModel performer = new SimilarPerformerViewModel();
                            performer.name = rec.performer.name;
                            performer.id = rec.performer.id;
                            performer.genres = rec.performer.genres;
                            performer.score = Math.Round(rec.performer.score*100,2); 
                            performer.image = rec.performer.image;
                            performer.url = rec.performer.url;
                            performer.OrigId = id;
                            ResultList.Add(performer);

                        }
                    
                }
            }
            return View(ResultList);
        }
    }
}
    

ConCon/Controllers/MapController.cs
using ConCon.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using Newtonsoft.Json;
using System.Web.Mvc;

namespace ConCon.Controllers
{
    public class MapController : Controller
    {
        // GET: Map

        public ActionResult MapView(int id)
        {
            var artists = SearchSimilar(id);
            List<string> artistNames = new List<string>();
            foreach (var artist in artists)
            {
                artistNames.Add(artist.name);
            }
            List<string> splitArtists = ArtistSplit(artistNames);
            return View(EventApiCall(splitArtists));
        }
        private List<string> ArtistSplit(List<string> artistNames)
        {
            List<string> correctedNames = new List<string>();
            foreach (string artist in artistNames)
            {
                if (artist.Contains(" "))
                {
                    string correctedName = null;
                    
                    string[] splitName = artist.ToLower().Split();
                    foreach (string name in splitName)
                    {
                        correctedName += name + "-";
                    }
                    string artistName = correctedName.Remove(correctedName.Length - 1);
                    correctedNames.Add(artistName);
                }
                else
                {
                    string lowerArtist = artist.ToLower();
                    correctedNames.Add(lowerArtist);
                }
            }
            return correctedNames;
        }
        private List<EventViewModel> EventApiCall(List<string> artists)
        {
            var settings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                MissingMemberHandling = MissingMemberHandling.Ignore,
            };
            List<EventViewModel> events = new List<EventViewModel>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.seatgeek.com/2/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                foreach (string artist in artists)
                {
                    string url = "https://api.seatgeek.com/2/events?performers.slug=" + artist + "&client_id=ODExNjMyNnwxNDk5Nzg0NzQxLjEy";
                    HttpResponseMessage response = client.GetAsync(url).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var jsonString = response.Content.ReadAsStringAsync();
                        MapViewRootObject result = JsonConvert.DeserializeObject<MapViewRootObject>(jsonString.Result,settings);
                        foreach (EventViewModel Event in result.events)
                        {
                            events.Add(Event);
                        }
                    }
                }
            }
            return events;
        }
        private List<SimilarPerformerViewModel> SearchSimilar(int origId)
        {
            List<SimilarPerformerViewModel> ResultList = new List<SimilarPerformerViewModel>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.seatgeek.com/2/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                string url = "https://api.seatgeek.com/2/recommendations/performers?performers.id=" + origId + "&client_id=ODExNjMyNnwxNDk5Nzg0NzQxLjEy";
                var response = client.GetAsync(url).Result;
                if (response.IsSuccessStatusCode)
                {
                    var result = response.Content.ReadAsStringAsync();
                    SimilarPerformerRootObjectViewModel PerformerList = JsonConvert.DeserializeObject<SimilarPerformerRootObjectViewModel>(result.Result);
                    foreach (RecommendationViewModel rec in PerformerList.recommendations)
                    {
                        SimilarPerformerViewModel performer = new SimilarPerformerViewModel();
                        performer = rec.performer;
                        ResultList.Add(performer);
                    }
                }
            }
            return ResultList;
        }
    }
}

ConCon/Views/ArtistSearch/Index.cshtml
@{ 
    ViewBag.Title = "ArtistSearchView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search for Artist</h2>

<p>Search for an artist you would like to find similar artists/concerts for.</p>

@Html.ActionLink("Start Search","Search","ArtistSearch")

ConCon/Views/ArtistSearch/Search.cshtml
@model ConCon.Models.ArtistSearchViewModel
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search For An Artist</h2>
<br />
@using (Html.BeginForm("SearchResult", "ArtistSearch"))
{
    <fieldset>
        <div class="form-group">
            @Html.LabelFor(m => m.Search, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Search, new { @class = "form-control", id = "searchInput" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Search Artist" onclick="post()" />
            </div>
        </div>
    </fieldset>
}
<script>

   function post() {
        var Search = $("#searchInput").val();
        $.ajax({
            type: "GET",
            url: "SearchResult",
            coontentType: "application/json",
            data: {
                "Search": Search
            },
            dataType: "json",

            success: function (data) {
                console.log(data) 
            },
            error: function (req, status, error) {
                console.log(req);
            }
        });
        return false;
   };
  
    </script>

ConCon/Views/ArtistSearch/SearchResult.cshtml
@model IEnumerable<ConCon.Models.PerformerViewModel>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search Result</h2>

<div>
    <p>Here is a list of the list of Artists that match the name you searched for. Select one with the "Search For Similar Artists" below to see a selection of like acts:</p>
    <br />
    <table>
        @foreach (ConCon.Models.PerformerViewModel performer in Model)
        {
            <tr>
                <th>
                    @if (performer.image != null)
                    {
                        <img src="@Html.DisplayFor(modelItem => performer.image)" alt="No Image" />
                    }
                    else
                    {
                        <img src="http://4vector.com/i/free-vector-default-profile-picture_099397_Default_Profile_Picture.png" alt="No Image" style="height: 10% ; width: 10%" />
                    }
                </th>
                <th>
                    @Html.DisplayFor(modelItem => performer.name)
                </th>
                @*<th>
                        @Html.Display(performer.genres?[0]?.name ?? "N/A")
                    </th>*@
                <th>
                    <a href="@Html.DisplayFor(modelItem => performer.url)">Check For Tickets</a>
                </th>
                <th>
                    @Html.ActionLink("Search For Similar Artists", "SearchSimilar", "ArtistSearch", new {id = performer.id }, new { })
                </th>
            </tr>
        }

    </table>
</div>

ConCon/Views/ArtistSearch/SearchSimilar.cshtml
@model IEnumerable<ConCon.Models.SimilarPerformerViewModel>
@{
    ViewBag.Title = "SearchSimilar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Similar Artists</h2>
<br />
<p>Here is a list of similar artists that match your search: </p>
<br />
@try
{
    @Html.ActionLink("View Artist's Upcoming Events", "MapView", "Map", new { id = Model.ToList()[0].OrigId }, new {@class ="Search"})
}
catch
{
    <p>Sorry, there are no similar artists to your selected search.</p>
    @Html.ActionLink("Go Back", "Search", "ArtistSearch")
    <img class ="shrug "src="https://i.ytimg.com/vi/lFjWA5w74nY/maxresdefault.jpg" width="700" />
}
<br />
<div>
    <table>
        @foreach (ConCon.Models.SimilarPerformerViewModel performer in Model.OrderByDescending(performer => performer.score))
        {
            <tr>
                <th>
                    @if (performer.image != null)
                    {
                        <img src="@Html.DisplayFor(modelItem => performer.image)" alt="No Image" />
                    }
                    else
                    {
                        <img src="http://4vector.com/i/free-vector-default-profile-picture_099397_Default_Profile_Picture.png" alt="No Image" style="height: 10% ; width: 10%" />
                    }
                </th>
                <th>
                    @Html.DisplayFor(modelItem => performer.name)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => performer.score)% Match
                </th>
                <th>
                    <a href="@Html.DisplayFor(modelItem => performer.url)">Check For Tickets</a>
                </th>
            </tr>

        }
    </table>
</div>
